export const storyData = [
  {
    name: 'its_villan',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: true,
  },
  {
    name: 'its_rocky',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: false,
  },
  {
    name: 'its_rocky',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: false,
  },
  {
    name: 'its_rocky',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: false,
  },
  {
    name: 'its_rocky',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: false,
  },
  {
    name: 'its_rocky',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: false,
  },
  {
    name: 'its_rocky',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: false,
  },
  {
    name: 'its_rocky',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: false,
  },
  {
    name: 'its_rocky',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: false,
  },
  {
    name: 'its_rocky',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: false,
  },
  {
    name: 'halloween',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: false,
  },
  {
    name: 'robert12',
    img: require('./assets/img/pic1.png'), // Ensure the file path is correct
    seen: true,
  },
];

export const postData = [
  {
    user_id: 123,
    name: 'Devil',
    image_url:
      'https://s3-alpha-sig.figma.com/img/1b00/a241/07daec11770c10cb49fdfb51fe57bd85?Expires=1717372800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=FlTjehHzuB2OMml5yCbwwwliw1uQkFut8X3OZnxdYSbhDfFxWCYIKBoTOd76~bpNSJGGr7Fjt0NyvoG8HB0TNy9qMghMgjHZYqh7mkjEQOEl5e89F0dhTnwBRCNvVPApuHnyR7GdLmZ7euF0~uc2qR-d-Ly09vZklf8L03RDVNutlBC5~vs~Ch5iexG3iy8VQUKTi1cLvILZHOEqYyEwnfQQ365BVqqLYyFC4lsein7jNJQpHfGcgDxEg-XzavcjPjIqttTNv~x7D6Gn21surulzWRzJ61FuqMAzjqt7ZeDPedS1mikF5bEo4~Wb8CIpMnfATHvFM-MLASYMDnc8zw__',
    caption: 'This is a caption',
    location: 'Location Name',
    created_at: new Date(),
    updated_at: new Date(),
    likes_count: 0,
    share_count: 10,
    comments_count: 0,
  },
  {
    name: 'SpiderMAn',
    user_id: 123,
    image_url:
      'https://s3-alpha-sig.figma.com/img/1b00/a241/07daec11770c10cb49fdfb51fe57bd85?Expires=1717372800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=FlTjehHzuB2OMml5yCbwwwliw1uQkFut8X3OZnxdYSbhDfFxWCYIKBoTOd76~bpNSJGGr7Fjt0NyvoG8HB0TNy9qMghMgjHZYqh7mkjEQOEl5e89F0dhTnwBRCNvVPApuHnyR7GdLmZ7euF0~uc2qR-d-Ly09vZklf8L03RDVNutlBC5~vs~Ch5iexG3iy8VQUKTi1cLvILZHOEqYyEwnfQQ365BVqqLYyFC4lsein7jNJQpHfGcgDxEg-XzavcjPjIqttTNv~x7D6Gn21surulzWRzJ61FuqMAzjqt7ZeDPedS1mikF5bEo4~Wb8CIpMnfATHvFM-MLASYMDnc8zw__',
    caption: 'This is a caption',
    location: 'Location Name',
    created_at: new Date(),
    updated_at: new Date(),
    likes_count: 0,
    share_count: 10,
    comments_count: 0,
  },
  {
    name: 'Shoya',
    user_id: 123,
    image_url:
      'https://images.pexels.com/photos/674010/pexels-photo-674010.jpeg?cs=srgb&dl=pexels-anjana-c-169994-674010.jpg&fm=jpg',
    caption: 'This is a caption',
    location: 'Location Name',
    created_at: new Date(),
    updated_at: new Date(),
    likes_count: 0,
    share_count: 10,
    comments_count: 0,
  },
  {
    name: 'Rocky',
    user_id: 123,
    image_url:
      'https://images.unsplash.com/photo-1575936123452-b67c3203c357?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    caption: 'This is a caption',
    location: 'Location Name',
    created_at: new Date(),
    updated_at: new Date(),
    likes_count: 0,
    share_count: 10,
    comments_count: 0,
  },
  {
    name: 'Luther',
    user_id: 123,
    image_url:
      'https://images.unsplash.com/photo-1575936123452-b67c3203c357?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    caption: 'This is a caption',
    location: 'Location Name',
    created_at: new Date(),
    updated_at: new Date(),
    likes_count: 0,
    share_count: 10,
    comments_count: 0,
  },
  {
    name: 'SkyDragon',
    user_id: 123,
    image_url:
      'https://images.unsplash.com/photo-1575936123452-b67c3203c357?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    caption: 'This is a caption',
    location: 'Location Name',
    created_at: new Date(),
    updated_at: new Date(),
    likes_count: 0,
    comments_count: 0,
    share_count: 10,
  },
  {
    name: 'Lucifer',
    user_id: 123,
    image_url:
      'https://images.unsplash.com/photo-1575936123452-b67c3203c357?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    caption: 'This is a caption',
    location: 'Location Name',
    created_at: new Date(),
    updated_at: new Date(),
    likes_count: 0,
    share_count: 10,
    comments_count: 0,
  },
];

export const notificationData = [
  {
    id: 1,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    activity: 'Like your post, 10 others',
    like: true,
    comment: false,
    follow: false,
    followRequst: false,
    share: false,
    time: 'just now',
    acitivityImage:
      'https://s3-alpha-sig.figma.com/img/7f89/9dd2/ca6bcd5d5bdff8cb6abcf3a4de308049?Expires=1717372800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=ZT5hB-lGFcMambwnLWwVP-rdCOawvVQZOmGq9yUYun0lF6OMuthZKBgUnzCjiFxTogw9DnWDqfYZukgbZ3gm~3OGoAgphVx4HDPshVJV89L9IdR5Tdhcxku06VJ-tD4UkfPFT1a5QQEcFLkOoxn3norwvsdDAta~VQwd-vHlknHZ2CuU22ZT7nuyQi9y7lOp7OALLXtGo9ZwPdXXO1zUhVgRjQiRxw~X-GMiB1haJplr0E1RMbZtMd6XGq66BdPIl88BTsrTE~UE81sGaIFL7zNqpuPvQSMLXynHrEoVigZSSfRXp4jbS7n1-lMF5jo2jsKd3k8jXVrKKfYWXEDSQQ__',
    isacitivityImage: true,
  },
  {
    id: 2,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    activity: 'Comment on your post',
    like: false,
    comment: true,
    follow: false,
    followRequst: false,
    share: false,
    time: '1min',
    acitivityImage:
      'https://s3-alpha-sig.figma.com/img/7f89/9dd2/ca6bcd5d5bdff8cb6abcf3a4de308049?Expires=1717372800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=ZT5hB-lGFcMambwnLWwVP-rdCOawvVQZOmGq9yUYun0lF6OMuthZKBgUnzCjiFxTogw9DnWDqfYZukgbZ3gm~3OGoAgphVx4HDPshVJV89L9IdR5Tdhcxku06VJ-tD4UkfPFT1a5QQEcFLkOoxn3norwvsdDAta~VQwd-vHlknHZ2CuU22ZT7nuyQi9y7lOp7OALLXtGo9ZwPdXXO1zUhVgRjQiRxw~X-GMiB1haJplr0E1RMbZtMd6XGq66BdPIl88BTsrTE~UE81sGaIFL7zNqpuPvQSMLXynHrEoVigZSSfRXp4jbS7n1-lMF5jo2jsKd3k8jXVrKKfYWXEDSQQ__',
    isacitivityImage: true,
  },
  {
    id: 3,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    activity: 'Started following you',
    like: false,
    comment: false,
    follow: true,
    followRequst: false,
    share: false,
    time: '5min ago',
    acitivityImage:
      'https://s3-alpha-sig.figma.com/img/7f89/9dd2/ca6bcd5d5bdff8cb6abcf3a4de308049?Expires=1717372800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=ZT5hB-lGFcMambwnLWwVP-rdCOawvVQZOmGq9yUYun0lF6OMuthZKBgUnzCjiFxTogw9DnWDqfYZukgbZ3gm~3OGoAgphVx4HDPshVJV89L9IdR5Tdhcxku06VJ-tD4UkfPFT1a5QQEcFLkOoxn3norwvsdDAta~VQwd-vHlknHZ2CuU22ZT7nuyQi9y7lOp7OALLXtGo9ZwPdXXO1zUhVgRjQiRxw~X-GMiB1haJplr0E1RMbZtMd6XGq66BdPIl88BTsrTE~UE81sGaIFL7zNqpuPvQSMLXynHrEoVigZSSfRXp4jbS7n1-lMF5jo2jsKd3k8jXVrKKfYWXEDSQQ__',
    isacitivityImage: false,
  },
  {
    id: 4,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    activity: 'Follow Request for you',
    like: false,
    comment: false,
    follow: false,
    followRequst: true,
    share: false,
    time: '10min ago',
    acitivityImage:
      'https://s3-alpha-sig.figma.com/img/7f89/9dd2/ca6bcd5d5bdff8cb6abcf3a4de308049?Expires=1717372800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=ZT5hB-lGFcMambwnLWwVP-rdCOawvVQZOmGq9yUYun0lF6OMuthZKBgUnzCjiFxTogw9DnWDqfYZukgbZ3gm~3OGoAgphVx4HDPshVJV89L9IdR5Tdhcxku06VJ-tD4UkfPFT1a5QQEcFLkOoxn3norwvsdDAta~VQwd-vHlknHZ2CuU22ZT7nuyQi9y7lOp7OALLXtGo9ZwPdXXO1zUhVgRjQiRxw~X-GMiB1haJplr0E1RMbZtMd6XGq66BdPIl88BTsrTE~UE81sGaIFL7zNqpuPvQSMLXynHrEoVigZSSfRXp4jbS7n1-lMF5jo2jsKd3k8jXVrKKfYWXEDSQQ__',
    isacitivityImage: false,
  },
  {
    id: 5,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    activity: 'Sheared your post',
    like: false,
    comment: false,
    follow: false,
    followRequst: false,
    share: true,
    time: '30min ago',
    acitivityImage:
      'https://s3-alpha-sig.figma.com/img/7f89/9dd2/ca6bcd5d5bdff8cb6abcf3a4de308049?Expires=1717372800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=ZT5hB-lGFcMambwnLWwVP-rdCOawvVQZOmGq9yUYun0lF6OMuthZKBgUnzCjiFxTogw9DnWDqfYZukgbZ3gm~3OGoAgphVx4HDPshVJV89L9IdR5Tdhcxku06VJ-tD4UkfPFT1a5QQEcFLkOoxn3norwvsdDAta~VQwd-vHlknHZ2CuU22ZT7nuyQi9y7lOp7OALLXtGo9ZwPdXXO1zUhVgRjQiRxw~X-GMiB1haJplr0E1RMbZtMd6XGq66BdPIl88BTsrTE~UE81sGaIFL7zNqpuPvQSMLXynHrEoVigZSSfRXp4jbS7n1-lMF5jo2jsKd3k8jXVrKKfYWXEDSQQ__',
    isacitivityImage: true,
  },
];

export const chatData = [
  {
    id: 1,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Hello david how are you?',
    chatCount: 1,
    isSeen: false,
    follow: false,
    followRequst: false,
    share: false,
    time: 'just now',
  },
  {
    id: 2,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'And stakeholders to align vision with execut...',
    chatCount: 1,
    isSeen: false,
    isOnline: true,
    followRequst: false,
    share: false,
    time: '1min',
  },
  {
    id: 3,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'And stakeholders to align vision with execution...',
    chatCount: 1,
    isSeen: false,
    isOnline: true,
    followRequst: false,
    share: false,
    time: '5min ago',
  },
  {
    id: 4,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Hello david how are you?',
    chatCount: 6,
    isSeen: false,
    isOnline: false,
    followRequst: true,
    share: false,
    time: '10min ago',
  },
  {
    id: 5,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Sent message',
    chatCount: 2,
    isSeen: true,
    isOnline: false,
    followRequst: false,
    share: true,
    time: '30min ago',
  },
  {
    id: 6,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Sent message',
    chatCount: 2,
    isSeen: true,
    isOnline: false,
    followRequst: false,
    share: true,
    time: '30min ago',
  },
  {
    id: 7,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Sent message',
    chatCount: 2,
    isSeen: true,
    isOnline: false,
    followRequst: false,
    share: true,
    time: '30min ago',
  },
  {
    id: 8,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Sent message',
    chatCount: 2,
    isSeen: true,
    isOnline: false,
    followRequst: false,
    share: true,
    time: '30min ago',
  },
  {
    id: 9,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Sent message',
    chatCount: 2,
    isSeen: true,
    isOnline: false,
    followRequst: false,
    share: true,
    time: '30min ago',
  },
  {
    id: 10,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Sent message',
    chatCount: 2,
    isSeen: true,
    isOnline: false,
    followRequst: false,
    share: true,
    time: '30min ago',
  },
  {
    id: 11,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Sent message',
    chatCount: 2,
    isSeen: true,
    isOnline: false,
    followRequst: false,
    share: true,
    time: '30min ago',
  },
  {
    id: 12,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Sent message',
    chatCount: 2,
    isSeen: true,
    isOnline: false,
    followRequst: false,
    share: true,
    time: '30min ago',
  },
  {
    id: 13,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Sent message',
    chatCount: 2,
    isSeen: true,
    isOnline: false,
    followRequst: false,
    share: true,
    time: '30min ago',
  },
  {
    id: 14,
    ProfileImage: require('./assets/img/pic1.png'),
    name: 'David Doe',
    chat: 'Sent message',
    chatCount: 2,
    isSeen: true,
    isOnline: false,
    followRequst: false,
    share: true,
    time: '30min ago',
  },
];
